name: Project CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Set artifact
        id: set-artifact
        run: |
          ARTIFACT_NAME=$(ls ./build/libs/*.jar | grep -v 'plain' | head -n 1 | xargs basename)
          echo "artifact=$ARTIFACT_NAME" >> $GITHUB_ENV

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./build/libs/${{ env.artifact }}"
          target: "/home/${{ secrets.EC2_USERNAME }}/app"

      - name: Run jar on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set +e  
        
            APP_DIR=/home/ubuntu/app
            JAR_NAME=g25Server.jar
            TARGET_JAR=$APP_DIR/g25Server.jar
            
            echo "ğŸ›‘ Stop existing jar"
            pkill -f 'java -jar'
            PKILL_STATUS=$?
            
            if [ "$PKILL_STATUS" -eq 0 ]; then
              echo "âœ… ê¸°ì¡´ í”„ë¡œì„¸ìŠ¤ ì •ìƒ ì¢…ë£Œ (pkill 0)"
            elif [ "$PKILL_STATUS" -eq 143 ]; then
              echo "âœ… ì •ìƒ ì¢…ë£Œëœ í”„ë¡œì„¸ìŠ¤ (SIGTERM - 143)"
            else
              echo "â„¹ï¸ ì¢…ë£Œí•  í”„ë¡œì„¸ìŠ¤ ì—†ìŒ ë˜ëŠ” ê¸°íƒ€ ìƒíƒœ ($PKILL_STATUS)"
            fi
            
            echo "â³ Waiting for process to stop..."
            for s in {1..50}; do
              if pgrep -f 'java -jar' > /dev/null; then
                echo "â³ still running 00:$s"
                sleep 1
              else
                echo "âœ… í”„ë¡œì„¸ìŠ¤ ì™„ì „íˆ ì¢…ë£Œë¨"
                break
              fi
            done
            
            echo "ğŸ§¹ Removing old JARs"
            rm -f $APP_DIR/*.jar
            
            
            echo "ğŸš€ Starting new application"
            nohup java -jar $TARGET_JAR > $APP_DIR/nohup.out 2>&1 &
            sleep 20
            
            echo "ğŸ” Checking Java process"
            pgrep -fl 'java -jar' && echo "âœ… ì‹¤í–‰ ì¤‘" || echo "âš ï¸ ì‹¤í–‰ ì•ˆë¨"
            
            echo "ğŸ‰ ë°°í¬ ì™„ë£Œ"
            exit 0
